export const CONTRACT_TEXT = {
  DEFINICOES:
    'Como “Software”, entende-se programa de computador que executa automaticamente rotinas para cumprir um determinado comando. “Módulo”, significa conjunto de rotinas específicas dentro do software, que podem ser ativadas ou desativadas de acordo com o que for contratado. “Rotinas”, entende-se como conjunto de operações a ser realizada no software pelo usuário para registrar as informações relativas a sequência de suas atividades ou tarefas. “Implantação”, compreende os processos de instalação, configuração, parametrização e treinamento. “Configuração”, entendesse como ajustar ou definir opções de uso de preferência do usuário, bem como os requisitos obrigatórios do software. “Parametrização”, entende-se como ajustar as regras contábeis e tributárias inerentes à atividade econômica, bem como ajustar as regras de negócio da contratante. “Treinamento”, significa ensinar os usuários a utilizar corretamente o software. “Customização”, significa desenvolver novas rotinas, relatórios ou realizar qualquer alteração no sistema que altere seu formato original de necessidade específica da contratante. “Manutenção do Software”, é realizada por meio de atualizações periódicas do software denominadas release. “Release”, é uma nova versão do software que contem melhorias de desempenho e operacionalidade, além de correções de erros informados por usuários ou outras fontes e acrescentam novas funções ou rotinas. “Suporte de Software”, esclarecimento de dúvidas, por meio de telefone ou chat relacionadas ao uso do software.',
  CONTRATADA:
    'CONTACTO SOLUÇÕES EM TECNOLOGIA - LTDA, pessoa jurídica de direito privado, inscrita no CNPJ sob o nº 27.751.577/0001-91, com sede na Rua Paulo de Vasconcelos, nº 429, Maria Ortiz, Vitoria-ES - CEP 29.070-364, neste ato representada pelo seu representante legal Rodrigo Goronci Sant’Ana, inscrito no CPF sob o nº 022.885.287-02 e RG sob o nº 1.165.84 SSP-ES.',
  INTRO:
    'As partes acima identificadas, ajustam de comum acordo, o presente Contrato de Licença de Uso e Serviços de Implantação, Manutenção e Suporte de Software entre pessoas jurídicas, que se regerá pelas cláusulas seguintes e pelas condições descritas no presente.',
  CLAUSULA_1: [
    '1.1) Este contrato tem por objeto a cessão do direito de uso do software TMS-SERVICE LOGIC, doravante denominado exclusivamente como SOFTWARE.',
    '1.2) A licença de uso concedida neste contrato dá a CONTRATANTE o direito, não exclusivo, mas intransferível, de usar o sistema unicamente para processamento de seus dados, em computadores de sua propriedade ou de sua responsabilidade, reservando o direito de propriedade exclusiva à contratada CONTACTO SOLUÇÕES EM TECNOLOGIA - LTDA.',
    '1.3) O serviço de Implantação é único, poderá ser realizado presencialmente e/ou remotamente.',
    '1.4) O serviço de Manutenção de Software contempla correções de erros gerados na codificação que impeçam o uso do sistema, novas implementações de melhorias estruturais do sistema ou alterações fiscais ou decorrentes de alterações legislativas/governamentais.',
    '1.5) O serviço de Suporte de Software corresponde ao esclarecimento de dúvidas do usuário que recebeu treinamento durante ou após o processo de implantação, como também resolver problemas oriundos do mau funcionamento do software, por meio de telefone, e-mail ou chat, com atendimento em horário comercial e plantões até as 22h e aos finais de semana até as 22h nos contatos, (27) 3500-1702 e suporte@servicelogic.com.br.',
    '1.6) A CONTRATANTE poderá cadastrar no sistema, sem custo adicional, apenas o CNPJ Matriz. Para o cadastro de CNPJ Filial será cobrado uma taxa adicional. O cadastro de um Novo CNPJ Matriz na mesma base de dados será cobrado à parte por meio de um novo contrato. (vide item 5.3).',
  ],
  CLAUSULA_2: [
    '2.1) Caso a CONTRATANTE necessite destes serviços, solicitará um orçamento e, havendo concordância das partes, o serviço será feito no prazo determinado, mediante o pagamento da hora técnica, despesas de transporte e alimentação.',
    '2.2) Melhorias solicitadas por interesse da CONTRATANTE não fazem parte do objeto desse contrato e, poderão ou não ser desenvolvidas pela CONTRATADA.',
    '2.3) Quando a solicitação for uma regra de negócio específica da CONTRATANTE, esta será considerada como customização. Neste caso, a CONTRATADA avaliará a viabilidade técnica e econômico-financeira, e apresentará o orçamento com o cronograma e o total de horas técnicas previstas para realização do serviço. Uma vez aprovado, o serviço será faturado de acordo com o valor da hora técnica padrão vigente no ato da confecção do orçamento (DET), além do pagamento das despesas de transporte, alimentação e tempo gasto para levantamento da solicitação.',
    '2.4) Não consta no objeto deste contrato o desenvolvimento de soluções personalizadas para exportação dos dados da CONTRATANTE, no caso de rescisão contratual. A contratação deste serviço será tratada como customização/novo projeto, sendo assim cobrada à parte.',
    '2.5) A CONTRATANTE poderá adquirir um novo módulo do software, mediante assinatura do Termo de inclusão/substituição de Produto, contendo as informações do produto que será disponibilizado, os valores, instalação e treinamento, mantendo-se inalteradas as demais cláusulas deste contrato.',
    '2.6) Após a implantação, para realizar novos treinamentos ou treinamentos de novos usuários do software, serão cobrados valores adicionais, mediante prévio orçamento com apresentação dos planos de treinamento disponíveis.',
  ],
  CLAUSULA_3: [
    '3.1) Fornecer as informações necessárias, disponibilizar pessoal e outros requisitos para a perfeita implantação do sistema.',
    '3.2) Verificar e manter amplo controle sobre as informações geradas pelo software, permitindo que apenas as pessoas treinadas pela CONTRATADA (usuários) possam operar o software.',
    '3.3) É de responsabilidade da CONTRATANTE, o ato de enviar os dados e arquivos gerados pelo software da CONTRATADA solicitados por órgãos ou entidades governamentais ou não e é responsabilidade da CONTRATADA manter em pleno funcionamento o meio como esse envio acontece.',
    '3.4) A CONTRATANTE, efetuará os pagamentos dos valores ajustados neste contrato, de acordo com as datas e condições estabelecidas, independentemente de sua efetiva utilização, posto que trata-se de um serviço contratado e disponibilizado ao CONTRATANTE, pela CONTRATADA.',
    '3.5) Fica a CONTRATANTE obrigado por si, seus herdeiros e sucessores a qualquer título, e a qualquer tempo, a cumprir o disposto no presente contrato.',
    '3.6) Caso o CONTRATANTE opte por instalar o software, objeto deste contrato, em um servidor contratado pela CONTRATANTE, a CONTRATANTE se obriga a manter backup atualizado de todas as informações constantes no banco de dados, bem como a manter em perfeito funcionamento a infraestrutura necessária para a utilização do software.',
  ],
  CLAUSULA_4: [
    '4.1) A CONTRATADA garante o funcionamento do software, de acordo com as especificações e características do mesmo.',
    '4.2) A CONTRATADA prestará o serviço de suporte sempre que solicitada pelo CONTRATANTE através de contato telefônico, e-mail ou chat online, sempre obedecendo os dias e horários divulgados em nossa central de atendimento.',
    '4.3) A CONTRATADA, prestará serviço de Manutenção ADAPTATIVA LEGAL, adequando o software às alterações da legislação vigente, Manutenção EVOLUTIVA, garantindo a atualização tecnológica do software, e ainda Manutenção CORRETIVA, corrigindo o mau funcionamento do software, sempre que gerado por erros em sua concepção e produção.',
  ],
  CLAUSULA_6: [
    '6.1) O serviço de Implantação/Treinamento inicia logo após a assinatura do contrato, sendo realizado de forma remota com a utilização de chamada telefônica (voz ou vídeo) ou presencial, de acordo com o contratado pela CONTRATANTE, respeitando a franquia máxima de horas pré-definida para cada módulo.',
    '6.2) A programação das datas e horários para realização da Implantação/Treinamento deverão ser definidas em comum acordo entre a CONTRATADA e a CONTRATANTE, devendo esta última disponibilizar seus funcionários para o melhor aproveitamento desta etapa.',
    '6.3) Após a conclusão da implantação/Treinamento, todo novo treinamento de reciclagem ou de novos usuários incorrerá em cobrança adicional, obedecendo o valor da hora técnica vigente no ato da contratação.',
  ],
  CLAUSULA_7: [
    '7.1) A CONTRATADA poderá divulgar, sem necessidade de qualquer tipo de comunicado ou remuneração, através de qualquer meio de comunicação, que o CONTRATANTE é um cliente da CONTRATADA e utiliza seus produtos e/ou serviços.',
  ],
  CLAUSULA_8: [
    '8.1) A CONTRATADA não se responsabilizará por problemas, erros, danos ou prejuízos advindos de decisões tomadas com base em informações, quaisquer que sejam, fornecidas pelo Software, objeto deste contrato, assim como não se responsabilizará por defeitos ou erros decorrentes de negligência, imprudência ou imperícia do CONTRATANTE, seus empregados ou prepostos na utilização do software licenciado, bem como, por problemas de “caso fortuito” ou “força maior”.',
    '8.2) Caso o CONTRATANTE opte por instalar o software, objeto deste contrato, em um servidor contratado pelo CONTRATANTE, a CONTRATADA não se responsabilizará por danos causados ao software/base de dados por “vírus” de computador, falhas de equipamentos, sistema operacional, instalações físicas e gerenciador de rede, e erros em programas específicos do CONTRATANTE ou de terceiros.',
    '8.3) A CONTRATADA não garante o desempenho do software, objeto deste contrato, assim como seu processamento, caso o CONTRATANTE utilize equipamento ou plataforma de hardware fabricado fora das especificações comumente estabelecidas pelos fabricantes, não acompanhe a evolução tecnológica em termos de equipamento ou plataforma de hardware, não atualize seu sistema operacional ou plataforma de software ou não acompanhe o lançamento de novas versões do Software.',
    '8.4) A CONTRATADA não se responsabiliza pela forma como o CONTRATANTE utiliza o software, nem pelo conteúdo dos dados, destino e fins das informações, nem tampouco pelas sanções que por ventura decorrerem do seu uso.',
  ],
  CLAUSULA_9: [
    '9.1) A CONTRATADA, por si e por seus colaboradores, obriga-se a atuar no presente Contrato em conformidade com a Legislação vigente sobre Proteção de Dados Pessoais e as determinações de órgãos reguladores/fiscalizadores sobre a matéria, em especial a Lei 13.709/2018, além das demais normas e políticas de proteção de dados de cada país onde houver qualquer tipo de tratamento dos dados dos clientes, o que inclui os dados da CONTRATANTE. No manuseio dos dados a CONTRATADA deverá:',
    '9.2) Tratar os dados pessoais a que tiver acesso apenas de acordo com as instruções da CONTRATANTE e em conformidade com estas cláusulas, e que, na eventualidade, de não mais poder cumprir estas obrigações, por qualquer razão, concorda em informar de modo formal este fato imediatamente à CONTRATANTE, que terá o direito de rescindir o contrato sem qualquer ônus, multa ou encargo.',
    '9.3) Manter e utilizar medidas de segurança administrativas, técnicas e físicas apropriadas e suficientes para proteger a confidencialidade e integridade de todos os dados pessoais mantidos ou consultados/transmitidos eletronicamente, para garantir a proteção desses dados contra acesso não autorizado, destruição, uso, modificação, divulgação ou perda acidental ou indevida.',
    '9.4) Acessar os dados dentro de seu escopo e na medida abrangida por sua permissão de acesso (autorização) e que os dados pessoais não podem ser lidos, copiados, modificados ou removidos sem autorização expressa e por escrito da CONTRATANTE.',
    '9.5) Garantir, por si própria ou quaisquer de seus empregados, prepostos, sócios, diretores, representantes ou terceiros contratados, a confidencialidade dos dados processados, assegurando que todos os seus colaboradores prepostos, sócios, diretores, representantes ou terceiros contratados que lidam com os dados pessoais sob responsabilidade da CONTRATANTE assinaram Acordo de Confidencialidade com a CONTRATADA, bem como a manter quaisquer Dados Pessoais estritamente confidenciais e de não os utilizar para outros fins, com exceção da prestação de serviços à CONTRATANTE. Ainda, treinará e orientará a sua equipe sobre as disposições legais aplicáveis em relação à proteção de dados.',
    '9.6) Os dados pessoais não poderão ser revelados a terceiros, com exceção da prévia autorização por escrito da CONTRATANTE, quer direta ou indiretamente, seja mediante a distribuição de cópias, resumos, compilações, extratos, análises, estudos ou outros meios que contenham ou de outra forma reflitam referidas Informações.',
    '9.7) Caso a CONTRATADA seja obrigada por determinação legal a fornecer dados pessoais a uma autoridade pública, deverá informar previamente a CONTRATANTE para que esta tome as medidas que julgar cabíveis.',
    '9.8) A CONTRATADA deverá notificar a CONTRATANTE em até 24 (vinte e quatro) horas a respeito de: i) Qualquer não cumprimento (ainda que suspeito) das disposições legais relativas à proteção de Dados Pessoais pela CONTRATADA, seus funcionários, ou terceiros autorizados; ii) Qualquer outra violação de segurança no âmbito das atividades e responsabilidades da CONTRATADA.',
  ],
  CLAUSULA_10: [
    '10.1) Fica eleito o Foro da Comarca de Serra, Estado do Espírito Santo, para dirimir eventuais dúvidas oriundas do presente contrato, podendo a CONTRATADA, a seu critério e liberalidade, optar pelo julgamento arbitral, conforme previsto em lei.',
  ],
}
