ALTER TABLE public.atividades_comerciais 
ADD COLUMN IF NOT EXISTS tipo TEXT,
ADD COLUMN IF NOT EXISTS acao_necessaria TEXT,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS data_follow_up DATE,
ADD COLUMN IF NOT EXISTS observacoes TEXT,
ADD COLUMN IF NOT EXISTS valor_mensalidade NUMERIC,
ADD COLUMN IF NOT EXISTS valor_implantacao NUMERIC,
ADD COLUMN IF NOT EXISTS condicao TEXT,
ADD COLUMN IF NOT EXISTS parcelas TEXT;
